import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { setGlobalOptions } from 'firebase-functions/v2';
import { initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
setGlobalOptions({region:'europe-west1'});
initializeApp(); const db=getFirestore(); const adminAuth=getAuth();
const roles={ADVISOR:'Class Advisor',HOD:'HOD',PRINCIPAL:'Principal',WARDEN:'Year Warden',COUNCILLOR:'Resident Councillor',SECURITY:'Security'};
const transitions={PENDING_ADVISOR:{role:roles.ADVISOR,next:'PENDING_HOD'},PENDING_HOD:{role:roles.HOD,next:'PENDING_PRINCIPAL'},PENDING_PRINCIPAL:{role:roles.PRINCIPAL,next:'PENDING_WARDEN'},PENDING_WARDEN:{role:roles.WARDEN,next:'PENDING_COUNCILLOR'},PENDING_COUNCILLOR:{role:roles.COUNCILLOR,next:'APPROVED'}};
async function actor(auth){if(!auth)throw new HttpsError('unauthenticated','Sign in required.');const s=await db.doc(`users/${auth.uid}`).get();if(!s.exists)throw new HttpsError('permission-denied','User profile missing.');return {id:auth.uid,...s.data()}}
function audit(ref,user,action,from,to,remarks=''){return ref.collection('auditLogs').add({userId:user.id,userName:user.displayName||'',role:user.role,action,previousStatus:from,newStatus:to,remarks,createdAt:FieldValue.serverTimestamp()})}
const clean=(value,max=120)=>String(value||'').trim().slice(0,max);
const mail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const registerStudent=onCall(async req=>{const data=req.data||{};const displayName=clean(data.displayName),email=clean(data.email,160).toLowerCase(),registerNumber=clean(data.registerNumber,40).toUpperCase(),department=clean(data.department,100),parentPhone=clean(data.parentPhone,30),year=Number(data.year);if(!displayName||!mail.test(email)||!registerNumber||!department||!parentPhone||!Number.isInteger(year)||year<1||year>4)throw new HttpsError('invalid-argument','Please provide valid student registration details.');if(typeof data.password!=='string'||data.password.length<8)throw new HttpsError('invalid-argument','Password must contain at least 8 characters.');const regRef=db.doc(`registerNumbers/${registerNumber}`);let created;try{created=await adminAuth.createUser({email,password:data.password,displayName});await db.runTransaction(async tx=>{const used=await tx.get(regRef);if(used.exists)throw new HttpsError('already-exists','This register number is already registered.');tx.set(regRef,{uid:created.uid,createdAt:FieldValue.serverTimestamp()});tx.set(db.doc(`users/${created.uid}`),{displayName,email,registerNumber,department,parentPhone,year,role:'Student',createdAt:FieldValue.serverTimestamp(),active:true});tx.set(db.doc(`students/${created.uid}`),{displayName,registerNumber,department,parentPhone,year,userId:created.uid,createdAt:FieldValue.serverTimestamp()});});return {uid:created.uid};}catch(error){if(created)await adminAuth.deleteUser(created.uid).catch(()=>{});if(error instanceof HttpsError)throw error;if(error.code==='auth/email-already-exists')throw new HttpsError('already-exists','An account already exists for this email.');throw new HttpsError('internal','Registration could not be completed.');}});
export const provisionUser=onCall(async req=>{const manager=await actor(req.auth);if(manager.role!==roles.COUNCILLOR)throw new HttpsError('permission-denied','Only the Resident Councillor can provision staff accounts.');const data=req.data||{};const role=clean(data.role,60),displayName=clean(data.displayName),email=clean(data.email,160).toLowerCase();if(!Object.values(roles).includes(role)||!displayName||!mail.test(email)||typeof data.password!=='string'||data.password.length<8)throw new HttpsError('invalid-argument','Enter a valid staff name, email, role, and password.');let created;try{created=await adminAuth.createUser({email,password:data.password,displayName});await db.doc(`users/${created.uid}`).set({displayName,email,role,department:clean(data.department,100),active:true,createdAt:FieldValue.serverTimestamp(),provisionedBy:manager.id});return {uid:created.uid};}catch(error){if(created)await adminAuth.deleteUser(created.uid).catch(()=>{});if(error.code==='auth/email-already-exists')throw new HttpsError('already-exists','An account already exists for this email.');throw new HttpsError('internal','Staff account could not be provisioned.');}});
export const createOutpass=onCall(async req=>{const u=await actor(req.auth);if(u.role!=='Student')throw new HttpsError('permission-denied','Students only.');const x=req.data;for(const k of ['reason','destination','outAt','returnAt','parentName','parentPhone'])if(!x[k])throw new HttpsError('invalid-argument',`${k} is required.`);if(new Date(x.returnAt)<=new Date(x.outAt))throw new HttpsError('invalid-argument','Return time must be after departure.');const ref=db.collection('outpasses').doc();const record={studentId:u.id,studentName:u.displayName,registerNumber:u.registerNumber,department:u.department,year:u.year,parentName:x.parentName,parentPhone:x.parentPhone,reason:x.reason,destination:x.destination,outAt:x.outAt,returnAt:x.returnAt,permissionLetterUrl:x.permissionLetterUrl||'',status:'PENDING_ADVISOR',approvals:[],createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};await ref.set(record);await audit(ref,u,'SUBMITTED','DRAFT','PENDING_ADVISOR');return {id:ref.id}});
export const processDecision=onCall(async req=>{const u=await actor(req.auth);const {outpassId,decision,remarks=''}=req.data;if(!['APPROVED','REJECTED'].includes(decision))throw new HttpsError('invalid-argument','Invalid decision.');if(decision==='REJECTED'&&!remarks.trim())throw new HttpsError('invalid-argument','A rejection reason is required.');const ref=db.doc(`outpasses/${outpassId}`);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Outpass not found.');const pass=s.data(), step=transitions[pass.status];if(!step||step.role!==u.role)throw new HttpsError('permission-denied','You cannot decide on this request at its current stage.');const next=decision==='REJECTED'?'REJECTED':step.next;const decidedAt=new Date();const entry={role:u.role,decision,name:u.displayName||'',at:decidedAt,remarks};const updates={status:next,approvals:[...(pass.approvals||[]),entry],updatedAt:FieldValue.serverTimestamp()};if(next==='APPROVED')updates.passNumber=`PASS-${outpassId.slice(0,8).toUpperCase()}`;tx.update(ref,updates);tx.set(ref.collection('approvals').doc(),{role:u.role,approverId:u.id,approverName:u.displayName,decision,remarks,decidedAt});tx.set(ref.collection('auditLogs').doc(),{userId:u.id,userName:u.displayName,role:u.role,action:decision,previousStatus:pass.status,newStatus:next,remarks,createdAt:FieldValue.serverTimestamp()});});return {ok:true}});
export const logGateMovement=onCall(async req=>{const u=await actor(req.auth);if(u.role!==roles.SECURITY)throw new HttpsError('permission-denied','Security staff only.');const {outpassId,action}=req.data;const ref=db.doc(`outpasses/${outpassId}`);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new HttpsError('not-found','Pass not found');const p=s.data();const valid=(action==='EXIT'&&p.status==='APPROVED')||(action==='RETURN'&&p.status==='CURRENTLY_OUT');if(!valid)throw new HttpsError('failed-precondition','Invalid gate transition.');const next=action==='EXIT'?'CURRENTLY_OUT':'CLEARED';tx.update(ref,{status:next,updatedAt:FieldValue.serverTimestamp()});tx.set(ref.collection('gateLogs').doc(),{securityId:u.id,securityName:u.displayName,action,at:FieldValue.serverTimestamp()});tx.set(ref.collection('auditLogs').doc(),{userId:u.id,userName:u.displayName,role:u.role,action,previousStatus:p.status,newStatus:next,createdAt:FieldValue.serverTimestamp()});});return {ok:true}});
