import assert from 'node:assert/strict';
const project='demo-campuspass';
const root=`http://${process.env.FIRESTORE_EMULATOR_HOST||'127.0.0.1:8080'}/v1/projects/${project}/databases/(default)/documents`;
const field=value=>value===null?{nullValue:null}:value instanceof Date?{timestampValue:value.toISOString()}:Array.isArray(value)?{arrayValue:{values:value.map(field)}}:typeof value==='object'?{mapValue:{fields:fields(value)}}:typeof value==='boolean'?{booleanValue:value}:typeof value==='number'?{integerValue:String(value)}:{stringValue:value};
const fields=value=>Object.fromEntries(Object.entries(value).map(([k,v])=>[k,field(v)]));
const token=uid=>[Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({iss:`https://securetoken.google.com/${project}`,aud:project,sub:uid,user_id:uid,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600,firebase:{sign_in_provider:'password'},email:`${uid}@example.test`})).toString('base64url'),''].join('.');
async function write(path,data,actor='owner'){const response=await fetch(`${root}/${path}`,{method:'PATCH',headers:{Authorization:`Bearer ${actor==='owner'?'owner':token(actor)}`,'Content-Type':'application/json'},body:JSON.stringify({fields:fields(data)})});return {status:response.status,body:await response.text()};}
async function register(uid,profile){const response=await fetch(root+':commit',{method:'POST',headers:{Authorization:`Bearer ${token(uid)}`,'Content-Type':'application/json'},body:JSON.stringify({writes:[{update:{name:`projects/${project}/databases/(default)/documents/users/${uid}`,fields:fields(profile)}},{update:{name:`projects/${project}/databases/(default)/documents/registerNumbers/${profile.registerNumber}`,fields:fields({uid,createdAt:new Date()})}}]})});return {status:response.status,body:await response.text()};}
const approved={active:true,approvalStatus:'APPROVED'};
for(const [uid,profile] of Object.entries({admin:{...approved,role:'Admin',displayName:'Admin'},advisor:{...approved,role:'Class Advisor',displayName:'Dr Advisor',department:'CSE'},inactive:{active:false,role:'HOD',displayName:'Inactive'},warden:{...approved,role:'Year Warden',displayName:'Warden',hostel:'Girls hostel'},principal:{...approved,role:'Principal',displayName:'Principal'},student:{...approved,role:'Student',displayName:'Student',department:'CSE',year:2,gender:'Female',section:'A'}}))assert.equal((await write(`users/${uid}`,profile)).status,200);
// Sign-in reads a missing session before claiming it. Admin access must support both operations.
let sessionRead=await fetch(`${root}/portalSessions/admin`,{headers:{Authorization:`Bearer ${token('admin')}`}});assert.equal(sessionRead.status,404);
const adminSession={sessionId:'admin-sign-in-session-0123456789',expiresAt:new Date(Date.now()+90000)};
let adminClaim=await write('portalSessions/admin',adminSession,'admin');assert.equal(adminClaim.status,200,adminClaim.body);
sessionRead=await fetch(`${root}/portalSessions/admin`,{headers:{Authorization:`Bearer ${token('admin')}`}});assert.equal(sessionRead.status,200);
sessionRead=await fetch(`${root}/portalSessions/admin`,{headers:{Authorization:`Bearer ${token('inactive')}`}});assert.equal(sessionRead.status,403);
const pass={studentId:'student',studentName:'Student',registerNumber:'REG1',department:'CSE',year:2,gender:'Female',section:'A',status:'PENDING_ADVISOR',approvals:[]};
assert.equal((await write('outpasses/one',pass)).status,200);
const entry={role:'Class Advisor',approverId:'advisor',name:'Dr Advisor',decision:'APPROVED',remarks:'',at:'2026-10-03'};
let result=await write('outpasses/one',{...pass,status:'PENDING_HOD',approvals:[entry]},'advisor');assert.equal(result.status,200,result.body);
result=await write('outpasses/one',{...pass,status:'PENDING_PRINCIPAL',approvals:[entry]},'inactive');assert.equal(result.status,403,result.body);
await write('outpasses/wrong-dept',{...pass,department:'EEE'});
result=await write('outpasses/wrong-dept',{...pass,department:'EEE',archived:true,archivedBy:'advisor'},'advisor');assert.equal(result.status,403,result.body);
await write('outpasses/duplicate',pass);
result=await write('outpasses/duplicate',{...pass,archived:true,archivedBy:'advisor'},'advisor');assert.equal(result.status,200,result.body);
const principalPass={...pass,status:'PENDING_PRINCIPAL',approvals:[entry]};await write('outpasses/routing',principalPass);
const principalEntry={role:'Principal',approverId:'principal',name:'Principal',decision:'APPROVED',remarks:'',at:'2026-10-03'};
result=await write('outpasses/routing',{...principalPass,status:'PENDING_WARDEN',hostel:'Boys hostel',approvals:[entry,principalEntry]},'principal');assert.equal(result.status,403,result.body);
result=await write('outpasses/routing',{...principalPass,status:'PENDING_WARDEN',hostel:'Girls hostel',approvals:[entry,principalEntry]},'principal');assert.equal(result.status,200,result.body);
result=await write('users/student',{...approved,role:'Student',displayName:'Student',department:'CSE',year:2,gender:'Female',section:'A',active:false,deleted:true,approvalStatus:'REMOVED'},'admin');assert.equal(result.status,200,result.body);
result=await write('users/admin',{role:'Admin',displayName:'Admin',active:false,approvalStatus:'REMOVED',deleted:true},'admin');assert.equal(result.status,403,result.body);
const disabledStudent={...approved,role:'Student',displayName:'Student',department:'CSE',year:2,gender:'Female',section:'A',active:false,disabled:true};
await write('users/student',disabledStudent);
result=await write('users/student',{...disabledStudent,active:true},'admin');assert.equal(result.status,403,result.body);
let blockedRead=await fetch(`${root}/outpasses/one`,{headers:{Authorization:`Bearer ${token('student')}`}});assert.equal(blockedRead.status,403);
await write('accountLocks/student',{deleted:true});
result=await write('users/student',{...disabledStudent,active:false,approvalStatus:'PENDING'},'student');assert.equal(result.status,403,result.body);
console.log('Firestore checks passed: workflow, scope, archive, disabled access, deleted-account protection and admin protection.');

const signup={displayName:'New Student',email:'newstudent@example.test',registerNumber:'NEW1',institution:'Engineering',department:'CSE',year:2,section:'A',gender:'Male',studentPhone:'9842012346',parentPhone:'9842012345',role:'Student',requestedRole:'Student',active:false,approvalStatus:'PENDING'};
result=await register('newstudent',signup);assert.equal(result.status,200,result.body);
result=await register('duplicate',{...signup,email:'duplicate@example.test'});assert.equal(result.status,403,result.body);
result=await register('matching',{...signup,email:'matching@example.test',registerNumber:'MATCH',studentPhone:signup.parentPhone});assert.equal(result.status,403,result.body);
result=await register('newhod',{...signup,email:'newhod@example.test',registerNumber:'HOD1',requestedRole:'HOD',year:null,section:'',studentPhone:'',parentPhone:'',phone:'9842012345'});assert.equal(result.status,200,result.body);

const liveStudent={...signup,displayName:'New Student',active:true,approvalStatus:'APPROVED'};await write('users/newstudent',liveStudent);
const futureOut=new Date(Date.now()+3600000),futureReturn=new Date(Date.now()+7200000);
const futurePass={studentId:'newstudent',studentName:'New Student',registerNumber:'NEW1',institution:'Engineering',department:'CSE',year:2,gender:'Male',section:'A',studentPhone:'9842012346',parentPhone:'9842012345',reason:'Family visit',category:'OUTING',studentType:'HOSTELLER',permissionPolicy:'FULL_APPROVAL',responsibilityAccepted:true,outAt:futureOut.toISOString(),returnAt:futureReturn.toISOString(),outAtTimestamp:futureOut,returnAtTimestamp:futureReturn,status:'PENDING_ADVISOR',approvals:[]};
result=await write('outpasses/future',futurePass,'newstudent');assert.equal(result.status,200,result.body);
result=await write('outpasses/changed-institute',{...futurePass,institution:'Arts'},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/matching-phone',{...futurePass,studentPhone:futurePass.parentPhone},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/reversed-dates',{...futurePass,returnAtTimestamp:new Date(Date.now())},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/emergency',{...futurePass,category:'EMERGENCY'},'newstudent');assert.equal(result.status,200,result.body);
result=await write('outpasses/wrong-category',{...futurePass,category:'BYPASS'},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/wrong-student-type',{...futurePass,studentType:'DAY_SCHOLAR'},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/wrong-permission',{...futurePass,permissionPolicy:'SKIP_APPROVAL'},'newstudent');assert.equal(result.status,403,result.body);
result=await write('outpasses/no-declaration',{...futurePass,responsibilityAccepted:false},'newstudent');assert.equal(result.status,403,result.body);
result=await write('users/newstudent',{...liveStudent,studentType:'DAY_SCHOLAR'},'admin');assert.equal(result.status,200,result.body);
result=await write('outpasses/day-scholar',{...futurePass,studentType:'DAY_SCHOLAR',category:'ON_DUTY'},'newstudent');assert.equal(result.status,200,result.body);

await write('users/hod-all-years',{...approved,displayName:'HOD',role:'HOD',institution:'Engineering',department:'CSE',year:4,section:'Z'});
const hodPass={...futurePass,status:'PENDING_HOD'};await write('outpasses/hod-scope',hodPass);
result=await write('outpasses/hod-scope',{...hodPass,status:'PENDING_PRINCIPAL',approvals:[{role:'HOD',approverId:'hod-all-years',name:'HOD',decision:'APPROVED',remarks:'',at:'2026-10-05'}]},'hod-all-years');assert.equal(result.status,200,result.body);
await write('users/institute-principal',{...approved,displayName:'Principal',role:'Principal',institution:'Arts'});
await write('outpasses/institute-scope',principalPass);
result=await write('outpasses/institute-scope',{...principalPass,status:'PENDING_WARDEN',hostel:'Girls hostel',approvals:[entry,{...principalEntry,approverId:'institute-principal'}]},'institute-principal');assert.equal(result.status,403,result.body);

const session={sessionId:'first-device-session-0123456789',expiresAt:new Date(Date.now()+90000)};
result=await write('portalSessions/newstudent',session,'newstudent');assert.equal(result.status,200,result.body);
result=await write('portalSessions/newstudent',{...session,sessionId:'second-device-session-0123456789'},'newstudent');assert.equal(result.status,403,result.body);
result=await write('portalSessions/newstudent',{...session,expiresAt:new Date(Date.now()+90000)},'newstudent');assert.equal(result.status,200,result.body);
await write('portalSessions/newstudent',{...session,expiresAt:new Date(Date.now()-1000)});
result=await write('portalSessions/newstudent',{...session,sessionId:'second-device-session-0123456789',expiresAt:new Date(Date.now()+90000)},'newstudent');assert.equal(result.status,200,result.body);

await write('users/security',{...approved,role:'Security',displayName:'Gate officer'});
await write('outpasses/locked-exit',{...futurePass,status:'APPROVED'});
result=await write('outpasses/locked-exit',{...futurePass,status:'CURRENTLY_OUT'},'security');assert.equal(result.status,403,result.body);
console.log('Document update checks passed: registration uniqueness, contacts, locked profiles, role scope, session leases and mandatory server gate validation.');

async function commit(actor,writes){const response=await fetch(root+':commit',{method:'POST',headers:{Authorization:`Bearer ${token(actor)}`,'Content-Type':'application/json'},body:JSON.stringify({writes})});return {status:response.status,body:await response.text()};}
const docName=path=>`projects/${project}/databases/(default)/documents/${path}`;
const update=(path,data)=>({update:{name:docName(path),fields:fields(data)}});
const engineering='STUDY WORLD COLLEGE OF ENGINEERING';
const staffBase={institution:'',department:'',year:null,section:'',hostel:'',position:'',gender:'',studentType:'',studentPhone:'',parentPhone:'',phone:'9842011111',photoUrl:'',disabled:false,deleted:false,active:true,approvalStatus:'APPROVED'};
await write('users/full-admin',{...staffBase,role:'Admin',requestedRole:'Admin',displayName:'Full Admin',registerNumber:'ADMIN1',position:'Registrar',email:'full-admin@example.test'});
await write('registerNumbers/ADMIN1',{uid:'full-admin',createdAt:new Date()});
const demoted={...staffBase,role:'Security',requestedRole:'Security',displayName:'Full Admin',registerNumber:'ADMIN1',email:'full-admin@example.test',reviewedAt:new Date(),updatedBy:'full-admin'};
result=await commit('full-admin',[update('users/full-admin',demoted)]);assert.equal(result.status,403,result.body);
result=await commit('admin',[update('users/full-admin',{...demoted,updatedBy:'admin'})]);assert.equal(result.status,200,result.body);
const createdStaff={...staffBase,role:'Security',requestedRole:'Security',displayName:'Gate Two',registerNumber:'STAFFNEW',email:'staffnew@example.test',phone:'9842012222'};
result=await commit('admin',[update('users/staff-new',createdStaff),update('registerNumbers/STAFFNEW',{uid:'staff-new',createdAt:new Date()})]);assert.equal(result.status,200,result.body);
result=await commit('admin',[update('users/staff-dup',{...createdStaff,displayName:'Gate Three',email:'staffdup@example.test',registerNumber:'STAFFNEW'}),update('registerNumbers/STAFFNEW',{uid:'staff-dup',createdAt:new Date()})]);assert.equal(result.status,403,result.body);
const shStudent={displayName:'First Year',email:'shstudent@example.test',registerNumber:'SHSTU1',institution:engineering,department:'SCIENCE AND HUMANITIES (S&H)',year:1,section:'A',gender:'Female',studentPhone:'9842012346',parentPhone:'9842012345',studentType:'HOSTELLER',role:'Student',requestedRole:'Student',active:true,approvalStatus:'APPROVED',disabled:false,deleted:false,phone:'',hostel:'',position:'',photoUrl:''};
result=await commit('admin',[update('users/sh-student',shStudent),update('registerNumbers/SHSTU1',{uid:'sh-student',createdAt:new Date()})]);assert.equal(result.status,200,result.body);
result=await commit('admin',[update('users/sh-student-late',{...shStudent,email:'shlate@example.test',registerNumber:'SHSTU2',year:2}),update('registerNumbers/SHSTU2',{uid:'sh-student-late',createdAt:new Date()})]);assert.equal(result.status,403,result.body);
await write('users/sh-advisor',{...approved,role:'Class Advisor',displayName:'S&H Advisor',institution:engineering,department:'s&h',year:1,section:'A',phone:'9842012345'});
const yearOne={...futurePass,institution:engineering,department:'EEE',year:1,section:'A',status:'PENDING_ADVISOR'};
await write('outpasses/sh-year1',yearOne);
const shEntry={role:'Class Advisor',approverId:'sh-advisor',name:'S&H Advisor',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/sh-year1',{...yearOne,status:'PENDING_HOD',approvals:[shEntry]},'sh-advisor');assert.equal(result.status,200,result.body);
const yearTwo={...yearOne,year:2};await write('outpasses/sh-year2',yearTwo);
result=await write('outpasses/sh-year2',{...yearTwo,status:'PENDING_HOD',approvals:[shEntry]},'sh-advisor');assert.equal(result.status,403,result.body);
const otherSection={...yearOne,section:'B'};await write('outpasses/sh-section',otherSection);
result=await write('outpasses/sh-section',{...otherSection,status:'PENDING_HOD',approvals:[shEntry]},'sh-advisor');assert.equal(result.status,403,result.body);
const artsPass={...yearOne,institution:'STUDY WORLD COLLEGE OF ARTS AND SCIENCE'};await write('outpasses/sh-arts',artsPass);
result=await write('outpasses/sh-arts',{...artsPass,status:'PENDING_HOD',approvals:[shEntry]},'sh-advisor');assert.equal(result.status,403,result.body);
const otherCollege={...yearOne,institution:'NORTH ENGINEERING COLLEGE'};await write('outpasses/sh-other-college',otherCollege);
result=await write('outpasses/sh-other-college',{...otherCollege,status:'PENDING_HOD',approvals:[shEntry]},'sh-advisor');assert.equal(result.status,403,result.body);
await write('users/sh-hod',{...approved,role:'HOD',displayName:'S&H HOD',institution:engineering,department:'SCIENCE AND HUMANITIES (S&H)',year:1,phone:'9842012345',sections:['A','B','C','D','E','F']});
await write('users/sh-hod-fg',{...approved,role:'HOD',displayName:'S&H HOD FG',institution:engineering,department:'SCIENCE AND HUMANITIES (S&H)',year:1,phone:'9842012345',sections:['F','G']});
const shHodPass={...yearOne,section:'B',status:'PENDING_HOD'};await write('outpasses/sh-hod',shHodPass);
const hodEntry={role:'HOD',approverId:'sh-hod',name:'S&H HOD',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/sh-hod',{...shHodPass,status:'PENDING_PRINCIPAL',approvals:[hodEntry]},'sh-hod');assert.equal(result.status,200,result.body);
result=await write('outpasses/sh-hod',{...shHodPass,status:'PENDING_PRINCIPAL',approvals:[{...hodEntry,approverId:'sh-hod-fg',name:'S&H HOD FG'}]},'sh-hod-fg');assert.equal(result.status,403,result.body);
const sectionG={...shHodPass,section:'G'};await write('outpasses/sh-hod-g',sectionG);
result=await write('outpasses/sh-hod-g',{...sectionG,status:'PENDING_PRINCIPAL',approvals:[hodEntry]},'sh-hod');assert.equal(result.status,403,result.body);
const fgEntry={role:'HOD',approverId:'sh-hod-fg',name:'S&H HOD FG',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/sh-hod-g',{...sectionG,status:'PENDING_PRINCIPAL',approvals:[fgEntry]},'sh-hod-fg');assert.equal(result.status,200,result.body);
const hodYearTwo={...shHodPass,year:2};await write('outpasses/sh-hod-year2',hodYearTwo);
result=await write('outpasses/sh-hod-year2',{...hodYearTwo,status:'PENDING_PRINCIPAL',approvals:[hodEntry]},'sh-hod');assert.equal(result.status,403,result.body);
console.log('Admin edit checks passed: self-lockout, duplicate IDs, and S&H coverage limited to first-year Engineering.');
const dayPass={...futurePass,studentType:'DAY_SCHOLAR',status:'PENDING_HOD'};await write('outpasses/day-hod',dayPass);
const dayHod={role:'HOD',approverId:'hod-all-years',name:'HOD',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/day-hod',{...dayPass,status:'APPROVED',passNumber:'PASS-DAYHOD',approvals:[dayHod]},'hod-all-years');assert.equal(result.status,200,result.body);
const hostellerHod={...futurePass,status:'PENDING_HOD'};await write('outpasses/hosteller-hod',hostellerHod);
result=await write('outpasses/hosteller-hod',{...hostellerHod,status:'APPROVED',passNumber:'PASS-HOSTEL',approvals:[dayHod]},'hod-all-years');assert.equal(result.status,403,result.body);
const holidayPass={...futurePass,category:'HOLIDAY',studentType:'DAY_SCHOLAR'};
result=await write('outpasses/holiday',holidayPass,'newstudent');assert.equal(result.status,200,result.body);
const lateWarden={...futurePass,status:'PENDING_WARDEN',year:4,gender:'Female',hostel:'Girls hostel'};await write('outpasses/warden-year',lateWarden);
const wardenEntry={role:'Year Warden',approverId:'warden',name:'Warden',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/warden-year',{...lateWarden,status:'PENDING_COUNCILLOR',approvals:[wardenEntry]},'warden');assert.equal(result.status,200,result.body);
await write('users/boys-warden',{...approved,role:'Year Warden',displayName:'Boys Warden',hostel:'Boys hostel'});
const maleWarden={...futurePass,status:'PENDING_WARDEN',gender:'Male'};await write('outpasses/warden-male',maleWarden);
result=await write('outpasses/warden-male',{...maleWarden,status:'PENDING_COUNCILLOR',approvals:[wardenEntry]},'warden');assert.equal(result.status,403,result.body);
const boysEntry={role:'Year Warden',approverId:'boys-warden',name:'Boys Warden',decision:'APPROVED',remarks:'',at:'2026-10-05'};
result=await write('outpasses/warden-male',{...maleWarden,status:'PENDING_COUNCILLOR',approvals:[boysEntry]},'boys-warden');assert.equal(result.status,200,result.body);
const femaleWarden={...futurePass,status:'PENDING_WARDEN',gender:'Female',hostel:'Boys hostel'};await write('outpasses/warden-female',femaleWarden);
result=await write('outpasses/warden-female',{...femaleWarden,status:'PENDING_COUNCILLOR',approvals:[boysEntry]},'boys-warden');assert.equal(result.status,403,result.body);
console.log('Workflow changes passed: day-scholar outpass at HOD, holiday category, and warden coverage across years.');
