import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'vite';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

test('portal markup presents the document-requested fields and separate admin overview', async () => {
  process.env.VITE_FIREBASE_API_KEY='';process.env.VITE_FIREBASE_PROJECT_ID='';
  const server=await createServer({server:{middlewareMode:true},appType:'custom',plugins:[{name:'portal-test-exports',enforce:'pre',transform(code,id){if(id.replaceAll('\\','/').endsWith('/src/App.jsx'))return code+'\nexport { ProfileFields, StudentHome, AdminOverview, RequestTable, OutpassForm, Portal };';}}]});
  try {
    const app=await server.ssrLoadModule('/src/App.jsx');
    const render=(component,props)=>renderToStaticMarkup(React.createElement(component,props));
    const form={institution:'',department:'',year:'',section:'',hostel:'',position:'',phone:'',studentPhone:'',parentPhone:'',gender:''};
    const fields=role=>render(app.ProfileFields,{form,set:()=>{},role});
    assert.match(fields('Principal'),/>Institution</);
    assert.doesNotMatch(fields('Principal'),/>Department<|>Year coverage<|>Section</);
    assert.doesNotMatch(fields('HOD'),/>Year coverage<|>Section</);
    assert.match(fields('HOD'),/>Department</);
    assert.doesNotMatch(fields('Resident Councillor'),/>Department<|>Year coverage</);
    assert.match(fields('Resident Councillor'),/>Official mobile number</);
    assert.match(fields('Admin'),/>Position</);
    assert.doesNotMatch(fields('Admin'),/>Department<|>Year coverage</);
    const login=render(app.CampusPassApp);
    assert.match(login,/Show password/);
    assert.match(login,/Create your CampusPass account/);
    assert.doesNotMatch(login,/Preview mode is active/);
    const home=render(app.StudentHome,{user:{registerNumber:'REG1'}});
    assert.match(home,/Your campus\. Your journey\./);
    assert.doesNotMatch(home,/student-meta|pass-card/);
    const overview=render(app.AdminOverview,{users:[],records:[],openApprovals:()=>{}});
    assert.match(overview,/Open user approvals/);
    assert.doesNotMatch(overview,/admin-table|Create approved access/);
    assert.match(overview,/Create users/);assert.match(overview,/Departments/);assert.match(overview,/Years &amp; sections/);assert.match(overview,/S&amp;H coverage/);
    const portal=render(app.Portal,{user:{uid:'admin',role:'Admin',displayName:'Ada Admin',active:true,approvalStatus:'APPROVED'},demo:true,logout:()=>{},notify:()=>{}});
    for (const label of ['Create users','Manage users','Roles &amp; coverage','Departments','Years &amp; sections','S&amp;H coverage']) assert.match(portal,new RegExp(label));
    const admin=await server.ssrLoadModule('/src/AdminWorkspace.jsx');
    const science=render(admin.ScienceCoverage,{users:[{uid:'sh',displayName:'Dr. Meera',email:'meera@example.test',registerNumber:'SH1',role:'Class Advisor',department:'SCIENCE AND HUMANITIES (S&H)',institution:'STUDY WORLD COLLEGE OF ENGINEERING',section:'A',approvalStatus:'APPROVED'}],currentUser:{uid:'admin'},demo:true,notify:()=>{}});
    assert.match(science,/common first year/);assert.match(science,/Year 2 and above/);assert.match(science,/Dr. Meera/);assert.match(science,/Edit role/);
    assert.match(science,/From section/);assert.match(science,/Assign section range/);assert.match(science,/S&amp;H HOD/);
    const createUser=render(admin.UserEditor,{currentUser:{uid:'admin'},demo:true,notify:()=>{}});
    assert.match(createUser,/Create a new user/);assert.match(createUser,/Temporary password/);assert.match(createUser,/Student type/);
    const editUser=render(admin.UserEditor,{person:{uid:'student',email:'student@example.test',role:'Student',approvalStatus:'APPROVED'},currentUser:{uid:'admin'},demo:true,notify:()=>{},close:()=>{}});
    assert.match(editUser,/Save account changes/);assert.match(editUser,/Archived/);assert.match(editUser,/Send password reset/);assert.match(editUser,/Permanently delete/);assert.doesNotMatch(editUser,/Temporary password/);
    const ownAccount=render(admin.UserEditor,{person:{uid:'admin',email:'admin@example.test',role:'Admin',approvalStatus:'APPROVED',displayName:'Ada Admin'},currentUser:{uid:'admin'},demo:true,notify:()=>{},close:()=>{}});
    assert.doesNotMatch(ownAccount,/Permanently delete/);
    const usersPage=render(admin.AdminUsers,{users:[{uid:'student',displayName:'Arun',email:'student@example.test',registerNumber:'REG1',role:'Student',approvalStatus:'APPROVED'}],currentUser:{uid:'admin'},demo:true,notify:()=>{},setUsers:()=>{}});
    assert.match(usersPage,/Permanently delete/);
    const sh=render(app.ProfileFields,{form:{...form,institution:'STUDY WORLD COLLEGE OF ENGINEERING',department:'SCIENCE AND HUMANITIES (S&H)'},set:()=>{},role:'Class Advisor'});
    assert.match(sh,/All sections/);assert.match(sh,/Common first-year Engineering/);assert.doesNotMatch(sh,/>Year coverage</);
    const requestTable=render(app.RequestTable,{records:[],role:'HOD',user:{},notify:()=>{}});
    assert.match(requestTable,/Departure date/);
    assert.doesNotMatch(requestTable,/>Year<|>Section</);
    const studentFields=fields('Student');
    assert.match(studentFields,/Student type/);
    assert.match(studentFields,/Day scholar/);
    const requestForm=render(app.OutpassForm,{user:{studentType:'DAY_SCHOLAR',studentPhone:'9842012346',parentPhone:'9842012345'},demo:true,notify:()=>{}});
    assert.match(requestForm,/Outing/);assert.match(requestForm,/Emergency/);assert.match(requestForm,/On duty/);assert.match(requestForm,/Holiday/);assert.match(requestForm,/Leave/);
    assert.match(requestForm,/9842012346/);assert.match(requestForm,/Filled from your student profile/);
    assert.match(requestForm,/outpass is generated when the HOD approves/);
    assert.doesNotMatch(requestForm,/Full campus approval|Student type|Day scholar/);
    const {PassCard}=await server.ssrLoadModule('/src/PassCard.jsx');
    const pass=render(PassCard,{record:{id:'TEST1',studentName:'Arun Kumar',studentType:'DAY_SCHOLAR',category:'ON_DUTY',status:'PENDING_HOD',approvals:[{role:'Class Advisor',decision:'APPROVED',name:'Dr. Meera'}]}});
    assert.match(pass,/pass-ticket/);assert.match(pass,/Permission trail/);
    assert.match(pass,/Day scholar/);assert.match(pass,/On duty/);assert.match(pass,/Security gate/);assert.match(pass,/Student in/);
    assert.match(pass,/Dr. Meera/);assert.doesNotMatch(pass,/Principal|Level 2 of 5|ticket-qr/);
    const studentPass=render(PassCard,{record:{id:'TEST1',studentName:'Arun Kumar',studentType:'HOSTELLER',category:'HOLIDAY',status:'PENDING_ADVISOR'},showStudentType:false});
    assert.match(studentPass,/Holiday/);assert.doesNotMatch(studentPass,/Hosteller|Permission level/);
    const returnedPass=render(PassCard,{record:{id:'TEST2',studentName:'Arun',studentType:'DAY_SCHOLAR',category:'EMERGENCY',status:'CLEARED',entryAt:'2026-10-05T10:00:00Z',responsibilityAccepted:true}});
    assert.match(returnedPass,/Returned to campus/);assert.match(returnedPass,/05\/10\/2026/);
    assert.match(returnedPass,/Student accepted responsibility/);
    assert.doesNotMatch(returnedPass,/ticket-qr/);
    const issuedPass=render(PassCard,{record:{id:'TEST3',studentName:'Arun',status:'APPROVED',outAt:'2026-10-05T08:00:00Z',returnAt:'2026-10-05T10:00:00Z'}});
    assert.match(issuedPass,/ticket-qr/);assert.match(issuedPass,/Print \/ save PDF/);
  } finally {await server.close();}
});
