import { useAcademicCatalog } from './academic-catalog';
import { roleFields, samePhone } from './profile-policy';
import { ROLES } from './workflow';
import { STUDENT_TYPES } from '../functions/outpass-policy';
import { isCommonFirstYear } from '../functions/academic-policy';

const withExisting=(values,value)=>value&&!values.includes(value)?[value,...values]:values;
export function InstitutionFields({form,set,department=true}){
  const {catalog}=useAcademicCatalog();
  const institutions=withExisting(catalog.institutions.map(x=>x.name),form.institution);
  const departments=withExisting(catalog.institutions.find(x=>x.name===form.institution)?.departments||[],form.department);
  return <><label>Institution<select value={form.institution||''} onChange={e=>{set('institution',e.target.value);set('department','')}} required><option value="">Choose institution</option>{institutions.map(x=><option key={x}>{x}</option>)}</select></label>{department&&<label>Department<select value={form.department||''} onChange={e=>set('department',e.target.value)} disabled={!form.institution} required><option value="">Choose department</option>{departments.map(x=><option key={x}>{x}</option>)}</select></label>}</>;
}
export function ProfileFields({form,set,role}){
  const {catalog}=useAcademicCatalog(),student=role===ROLES.STUDENT,fields=roleFields(role),common=isCommonFirstYear({...form,role});
  return <>{student&&<label>Student type<select value={form.studentType||'HOSTELLER'} onChange={e=>set('studentType',e.target.value)} required>{Object.entries(STUDENT_TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}{fields.institution&&<InstitutionFields form={form} set={set} department={fields.department}/>} {common&&<div className="scope-note"><b>S&H · Common first-year Engineering</b><p>This assignment covers Year 1 students across every Engineering department.{role===ROLES.ADVISOR?' Choose a section or cover all sections.':''}</p></div>}{fields.year&&!common&&<label>{student?'Year':'Year coverage'}<select value={form.year||''} onChange={e=>set('year',e.target.value)} required><option value="">Choose year</option>{withExisting(catalog.years,Number(form.year)||null).map(x=><option key={x} value={x}>Year {x}</option>)}</select></label>}{fields.section&&<label>Section<select value={form.section||''} onChange={e=>set('section',e.target.value)} required={!common}><option value="">{common?'All sections':'Choose section'}</option>{withExisting(catalog.sections,form.section).map(x=><option key={x}>{x}</option>)}</select></label>}{student&&<label>Gender<select value={form.gender||''} onChange={e=>set('gender',e.target.value)} required><option value="">Choose gender</option><option>Female</option><option>Male</option><option>Other</option></select></label>}{fields.hostel&&<label>Hostel coverage<select value={form.hostel||''} onChange={e=>set('hostel',e.target.value)} required><option value="">Choose hostel</option><option>Boys hostel</option><option>Girls hostel</option></select></label>}{fields.position&&<label>Position<input value={form.position||''} onChange={e=>set('position',e.target.value)} required/></label>}{student?<><label>Student mobile number<input type="tel" value={form.studentPhone||''} onChange={e=>set('studentPhone',e.target.value)} required/></label><label>Parent mobile number<input type="tel" value={form.parentPhone||''} onChange={e=>set('parentPhone',e.target.value)} required/></label>{samePhone(form.studentPhone,form.parentPhone)&&<p className="error" role="alert">Student and parent mobile numbers must be different.</p>}</>:<label>Official mobile number<input type="tel" value={form.phone||''} onChange={e=>set('phone',e.target.value)} required/></label>}</>;
}
